spring:
  profiles:
    active: dev

---

spring:
  profiles: mock

startRoute: timer:hello?period=10000
fromRoute: file:data/input?delete=true&readLock=none
toRoute1: mock:output



logging:
  level:
    cl.osvaldo.camel.democamelspring: DEBUG
camel:
  springboot:
    shutdown-timeout: 2

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/camel
    username: postgres
    password: welcome1


startRoute: timer:hello?period=10000
fromRoute: file:data/input?delete=true&readLock=none&moveFailed=error
toRoute1: file:data/output



logging:
  level:
    cl.osvaldo.camel.democamelspring: DEBUG
camel:
  springboot:
    shutdown-timeout: 2
---

spring:
  profiles: stage

startRoute: timer:hello?period=10000
fromRoute: file:data/stage/input?delete=true&readLock=none
toRoute1: file:data/output

logging:
  level:
    cl.osvaldo.camel.democamelspring: DEBUG

---

spring:
  profiles: prd

startRoute: timer:hello?period=10000
fromRoute: file:data/prod/input?delete=true&readLock=none
toRoute1: file:data/output

logging:
  level:
    cl.osvaldo.camel.democamelspring: INFO